CREATE SCHEMA IF NOT EXISTS MORTGAGE_REFERENCE;

CREATE TABLE IF NOT EXISTS MORTGAGE_REFERENCE.CUSTOMERS (
  CUSTOMER_ID VARCHAR NOT NULL,
  FULL_NAME VARCHAR NOT NULL,
  SEGMENT VARCHAR NOT NULL,
  PROVINCE VARCHAR NOT NULL,
  BRANCH_ID VARCHAR NOT NULL,
  BRANCH_NAME VARCHAR NOT NULL,
  PRIMARY_ADVISOR_ID VARCHAR NOT NULL,
  PRIMARY_ADVISOR_NAME VARCHAR NOT NULL,
  TENURE_YEARS NUMBER NOT NULL,
  PRODUCTS_HELD NUMBER NOT NULL,
  PRIMARY_RELATIONSHIP_FLAG VARCHAR NOT NULL,
  ORIGINATION_CHANNEL VARCHAR NOT NULL,
  DIGITAL_ENGAGEMENT_SCORE NUMBER NOT NULL,
  NPS_SCORE NUMBER NOT NULL,
  PREFERRED_LANGUAGE VARCHAR NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS MORTGAGE_REFERENCE.BRANCH_PERFORMANCE (
  BRANCH_ID VARCHAR NOT NULL,
  BRANCH_NAME VARCHAR NOT NULL,
  PROVINCE VARCHAR NOT NULL,
  BRANCH_MANAGER VARCHAR NOT NULL,
  RENEWALS_NEXT_180D NUMBER NOT NULL,
  BALANCE_MATURING_CAD FLOAT NOT NULL,
  HIGH_RISK_COUNT NUMBER NOT NULL,
  ANNUAL_REVENUE_AT_RISK_CAD FLOAT NOT NULL,
  RETENTION_RATE_LAST_QUARTER_PCT FLOAT NOT NULL,
  AVG_DISCOUNT_GRANTED_BPS FLOAT NOT NULL,
  ADVISOR_CAPACITY_FILES_PER_FTE NUMBER NOT NULL,
  AS_OF_DATE DATE NOT NULL,
  PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE IF NOT EXISTS MORTGAGE_REFERENCE.RETENTION_OFFERS (
  OFFER_ID VARCHAR NOT NULL,
  OFFER_NAME VARCHAR NOT NULL,
  ELIGIBLE_SEGMENTS VARCHAR NOT NULL,
  MAX_DISCOUNT_BPS NUMBER NOT NULL,
  CASHBACK_CAD FLOAT NOT NULL,
  REQUIRED_APPROVAL_LEVEL VARCHAR NOT NULL,
  NOTES VARCHAR NOT NULL,
  PRIMARY KEY (OFFER_ID)
);
